/**
 * Outlines the "RAUH-Welt" logotype into SVG paths (src/lib/logo.ts).
 *
 * The brand's own lettering is a heavy bracketed slab (Clarendon/Egyptienne
 * black family). Its original typeface is not freely licensed, so the closest
 * open match is used: Ultra (Astigmatic, SIL OFL 1.1). Paths are generated at
 * build time so the DOM logo and the WebGL ink mask share exact geometry and
 * no display font has to load in the browser.
 *
 *   node tools/build-logo.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import opentype from 'opentype.js';

const root = new URL('../', import.meta.url);
const fontFile = fileURLToPath(new URL('node_modules/@fontsource/ultra/files/ultra-latin-400-normal.woff', root));
const TEXT = 'RAUH-Welt';
const SIZE = 100; // units per em in the output; height ends up ≈ cap height
const TRACKING = 1.5; // the original lockup breathes slightly between letters (units)

const buf = readFileSync(fontFile);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

// lay out glyph by glyph with kerning + tracking
const glyphs = font.stringToGlyphs(TEXT);
const scale = SIZE / font.unitsPerEm;
let x = 0;
const placed = glyphs.map((g, i) => {
  const path = g.getPath(x, 0, SIZE);
  const out = { char: TEXT[i], path };
  const next = glyphs[i + 1];
  x += g.advanceWidth * scale + (next ? font.getKerningValue(g, next) * scale + TRACKING : 0);
  return out;
});

// tight bounding box of the whole word
const boxes = placed.map((p) => p.path.getBoundingBox());
const minX = Math.min(...boxes.map((b) => b.x1));
const minY = Math.min(...boxes.map((b) => b.y1));
const maxX = Math.max(...boxes.map((b) => b.x2));
const maxY = Math.max(...boxes.map((b) => b.y2));
const r = (v) => +v.toFixed(2);

const out = placed.map(({ char, path }, i) => {
  // shift so the word's bbox starts at 0,0
  path.commands.forEach((c) => {
    for (const k of ['x', 'y', 'x1', 'y1', 'x2', 'y2']) {
      if (k in c) c[k] = k.startsWith('x') ? c[k] - minX : c[k] - minY;
    }
  });
  const b = boxes[i];
  return { char, x: r(b.x1 - minX), w: r(b.x2 - b.x1), d: path.toPathData(2) };
});

const width = r(maxX - minX);
const height = r(maxY - minY);
const src = `// Generated by tools/build-logo.mjs — do not edit by hand.
// "RAUH-Welt" outlined from Ultra (Astigmatic, SIL Open Font License 1.1),
// the closest open match to the brand's heavy slab-serif lettering.

export interface LogoGlyph {
  char: string;
  /** left edge of the glyph's ink box */
  x: number;
  /** ink width */
  w: number;
  /** absolute path data in logo units */
  d: string;
}

export const LOGO = {
  text: ${JSON.stringify(TEXT)},
  width: ${width},
  height: ${height},
  glyphs: ${JSON.stringify(out, null, 2)} as LogoGlyph[],
};
`;
writeFileSync(new URL('src/lib/logo.ts', root), src);
console.log(`logo ${width} × ${height} (aspect ${(width / height).toFixed(2)})`);
